<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
        'Imbo\Module'                               => __DIR__ . '/src/Imbo/Module.php',
        'Imbo\ModuleTest'                => __DIR__ . '/tests/unit/Imbo/ModuleTest.php',
        );

