<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
        'Imbo\Client'                               => __DIR__ . '/src/Imbo/Client.php',
        'Imbo\Client\Module'                        => __DIR__ . '/Module.php',
        'Imbo\Client\Framework\TestCase'        => __DIR__ . '/tests/ImboClient/Framework/TestCase.php',
        'Imbo\Client\ClientTest'                => __DIR__ . '/tests/unit/Imbo/Client/ClientTest.php',
        );

